### ISSUE TITLE
[Feature Request] Support for dividend pool contracts

### ISSUE THREAD

**Issue by callmeajs** [PolyPup-Farm/polypup-ui-alpha-testers#55] opened 2021-09-13 23:51 UTC
Add support for dividend pools, see below for example pools.

Details:
Contract - 0x00537eEE39aBea48533696aAaa1266080eC94D7E 
Contract - 0x768cc7c311Bf62d63FeBEA5bAf798AFEEa4D09AE
Contract - 0xC3bC84514ED96Fa2B619208F772b571231599329

**Comment by Polypup** [comment] 2021-09-14 08:12
duplicate of #18

**Closed by Polypup** 2021-09-14 08:12 UTC
